ENV["AWS_PUBLIC"] = "AKIAJZQ37T4XQ5YT5J4Q"
ENV["AWS_SECRET"] = "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"
ENV["LINK_PUBLIC"] = "xzipm18ikgbqzhbcllcevirx4gvo5y43"
ENV["LINK_SECRET"] = "rCvgTrHVyJFhN1iWDvezT3aTS0OxqB0l"
